### ISSUE TITLE
Refactor Runner handling

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/court-scraper#97]
> Related to #91 and #61

Refactor handling of runners to support different call signatures of Site classes (Odyssey, Oscn, Wiscourts) and their search methods. Options:

- Update cli.py to find and invoke platform-specific runners (e.g. `oscn/runner.py`)
- Registry of site types and their related runners (seems wasteful to add this in sites_meta.csv, so probably should go in cli.py)

## Tasks

Refactor `Runner` handling 

- [x] Refactor `cli.py` to invoke runners from inside platform-specific modules (e.g. `oscn/runner.py`,`odyssey_site/runner.py`) in orde
- [x] Add `oscn/runner.py`
- [x] Add cli integration test for oscn
